--ROUND()
SELECT ROUND(1234.5678, 1) FROM DUAL;
SELECT ROUND(1234.5678, 0) FROM DUAL;
SELECT ROUND(1234.5678, -1) FROM DUAL;

--TRUNC()
SELECT TRUNC(1234.5678, 1) FROM DUAL;
SELECT TRUNC(1234.5678, 0) FROM DUAL;
SELECT TRUNC(1234.5678, -1) FROM DUAL;

--CEIL() 정수 중에 큰 수
SELECT CEIL(3.14), CEIL(-3.14) FROM DUAL;

--FLOOR() 정수 중에 작은 수
SELECT FLOOR(3.14), FLOOR(-3.14) FROM DUAL;

--MOD()
SELECT MOD(2, 3) FROM DUAL;

--SYSDATE
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';
SELECT SYSDATE FROM DUAL;

--ADD_MONTHS()
SELECT hiredate, ADD_MONTHS(hiredate+1,4) FROM emp;
SELECT hiredate, ADD_MONTHS(hiredate, 120) FROM emp;
SELECT hiredate, hiredate+40*365 FROM emp;
SELECT ename FROM emp WHERE hiredate+50*365 > SYSDATE;

--MONTHS_BETWEEN()
SELECT TRUNC(MONTHS_BETWEEN(SYSDATE, hiredate)/12, 0) AS year FROM emp;
--NEXT_DAY()
SELECT SYSDATE, NEXT_DAY(SYSDATE, '월') FROM DUAL;

SELECT ROUND(SYSDATE, 'CC') FROM DUAL;
SELECT ROUND(SYSDATE, 'YYYY') FROM DUAL;
SELECT ROUND(SYSDATE, 'DDD') FROM DUAL;
SELECT ROUND(SYSDATE, 'HH') FROM DUAL;

SELECT TRUNC(SYSDATE, 'DDD') FROM DUAL;
SELECT TRUNC(SYSDATE, 'HH') FROM DUAL;

--형변환함수
--자동형변환가능
SELECT empno, empno+'500' FROM emp;
SELECT empno, empno+TO_NUMBER(500) AS convert FROM emp;
--자동형변환불가능
SELECT empno, empno+'ABC' FROM emp;
--형변환 일어나지 않은 경우
SELECT empno, empno||'ABC' AS concat FROM emp;

SELECT TO_CHAR(SYSDATE, 'YY-MM-DD HH24:MI:SS') FROM DUAL;
